---

- name: Add the user 'baptiste' to the right groups
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/bash
    group: "{{ ansible_env.USER }}"
    groups: "{{ ansible_env.USER }},cdrom,floppy,sudo,audio,dip,video,plugdev,netdev,lpadmin,libvirt,kvm"
    append: true
    state: present
  become: true
