---
- name: Install 'gui' Linux packages
  become: true
  ansible.builtin.package:
    name:
      - bruno
      - calibre
      - dbeaver-ce
      - evince
      - gparted
      - kdocker
      - libreoffice
      - peek
      - ristretto             # XFCE image viewer
      - thunar                # XFCE file manager
      - thunar-archive-plugin # Archive support for Thunar
      #- thunar-dropbox-plugin # Dropbox support for Thunar FIXME: Requires the 'contrib' Debian repo
      - webp-pixbuf-loader    # WebP image format support for Ristretto
      - wl-clipboard
      - xclip
      - xsel
